#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 9
  - 8

before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

#运行的脚本命令
script:
  - npm run cov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  yarn: true
  directories:
    - node_modules

on:
  branch: 
    - master
    - dev